# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.32
# 

Name:       harbour-slumber

# >> macros
# << macros

%{!?qtc_qmake:%define qtc_qmake %qmake}
%{!?qtc_qmake5:%define qtc_qmake5 %qmake5}
%{!?qtc_make:%define qtc_make make}
%{?qtc_builddir:%define _builddir %qtc_builddir}
Summary:    Slumber Sleeptimer
Version:    0.16
Release:    1
Group:      Qt/Qt
License:    GPLv2
URL:        https://github.com/jgibbon/slumber
Source0:    %{name}-%{version}.tar.bz2
# Source100:  harbour-slumber.yaml
Requires:   sailfishsilica-qt5 >= 0.10.9
Requires:   qt5-qtdeclarative-import-sensors
Requires:   nemo-qml-plugin-dbus-qt5
BuildRequires:  pkgconfig(sailfishapp) >= 1.0.2
BuildRequires:  pkgconfig(Qt5Core)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5DBus)
BuildRequires:  desktop-file-utils

%description
Slumber is a Sleep Timer to pause your (native) media Applications or Kodi after a certain amount of time has passed. You can reset the Timer by moving your Device.

# This description section includes metadata for SailfishOS:Chum, see
# https://github.com/sailfishos-chum/main/blob/main/Metadata.md
%if 0%{?_chum}
Title: slumber sleep timer
Type: desktop-application
DeveloperName: J. Gibbon
DescriptionMD: https://github.com/jgibbon/slumber/raw/master/README.md
Categories:
- Utility
- AudioVideo
Custom:
  Repo: https://github.com/jgibbon/slumber.git
PackageIcon: https://github.com/jgibbon/slumber/raw/master/main/appicons/256x256/apps/harbour-slumber.png
Screenshots:
 - https://github.com/jgibbon/slumber/raw/master/meta/screenshot-screenshot-actions-v02.png
 - https://github.com/jgibbon/slumber/raw/master/meta/screenshot-screenshot-options-v02.png
 - https://github.com/jgibbon/slumber/raw/master/meta/screenshot-screenshot-reset-v02.png
Links:
  Homepage: https://github.com/jgibbon/slumber
  Bugtracker: https://github.com/jgibbon/slumber/issues
  Donation: https://www.paypal.me/jgibbon
%endif

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre


%qmake5

%make_build

#%qtc_qmake5

#%qtc_make %{?_smp_mflags}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%qmake5_install

# >> install post
# << install post

desktop-file-install --delete-original       \
  --dir %{buildroot}%{_datadir}/applications             \
   %{buildroot}%{_datadir}/applications/*.desktop

%files
%defattr(-,root,root,-)
%{_bindir}
%{_datadir}/%{name}
%{_datadir}/applications/%{name}.desktop
%{_datadir}/icons/hicolor/86x86/apps/%{name}.png
%{_datadir}/icons/hicolor/108x108/apps/%{name}.png
%{_datadir}/icons/hicolor/128x128/apps/%{name}.png
%{_datadir}/icons/hicolor/172x172/apps/%{name}.png
%{_datadir}/icons/hicolor/256x256/apps/%{name}.png
# >> files
# << files
